name: flutter_branch_sdk
description: Flutter Plugin for create deep link using Brach SDK (https://branch.io). This plugin provides a cross-platform (iOS, Android).
version: 2.0.0-nullsafety.3
homepage: https://github.com/RodrigoSMarques/flutter_branch_sdk

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

flutter:
  plugin:
    platforms:
      android:
        package: br.com.rsmarques.flutter_branch_sdk
        pluginClass: FlutterBranchSdkPlugin
      ios:
        pluginClass: FlutterBranchSdkPlugin
      web:
        default_package: FlutterBranchSdkWeb

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
